### ISSUE TITLE
The mirror.php doesn't download the packages.json

### ISSUE THREAD

**Issue by peter279k** [composer/mirror#6]
After following the [step](https://github.com/composer/mirror#setup) to accomplish the Composer V2 mirror server, it seems that the `mirror.php` doesn't download the `packages.json` on specific targeted directory defined on `mirror.config.php` file.

It only has the `p2` directory on above directory. And I also use the `supervisor` service to let `mirror.php` run on background process.

Could anyone know this problem? Thanks.

**Comment by Levivb** [comment]
Do you have `v1` mirror enabled? This mirror isn't fully tested with only `v2` as I understood from Jordi: https://github.com/composer/mirror/issues/3#issuecomment-717512559

**Comment by peter279k** [comment]
@Levivb, thanks for your reply.

I don't have the `v1` mirror. That is, it doesn't have the `p` directory on my specific targeted directory.

**Comment by peter279k** [comment]
After I re-enabling the `v1` mirror, I only have the `p` and `p2` folder.

But the `pckages.json` file isn't on above targeted directory.

**Comment by peter279k** [comment]
After re-enabling the `v1` mirror and run the `mirror.php --v1` and `mirror.php --v2` again on my background processes, it seems to be worked successfully.

**Comment by Seldaek** [comment]
Normally it should work with only v2, but you then have to configure https://github.com/composer/mirror/blob/master/mirror.config.php.dist#L19 to `false` if you don't run the --v1 script. Did you do that?

**Comment by peter279k** [comment]
> Normally it should work with only v2, but you then have to configure https://github.com/composer/mirror/blob/master/mirror.config.php.dist#L19 to `false` if you don't run the --v1 script. Did you do that?

After I configure that, it's worked.

**Comment by Seldaek** [comment]
Ok makes sense, it wasn't super well documented :D 

Fixed in https://github.com/composer/mirror/commit/25dbc0591eb3903b385123caa7b3a39bd7d41bd0
